Actress Elizabeth Taylor , 58 was admitted to Daniel Freeman Marina Hospital on April 8 with a sinus infection and was transferred to St . John 's Hospital in Santa Monica on April 16
because of a persistent fever and viral pneumonia .
She later underwent a biopsy that showed that Miss Taylor was suffering from bacterial pneumonia and a yeast infection that almost resulted in her death .
Miss Taylor suffered a nearly fatal bout with pneumonia in 1961 and underwent a tracheotomy to help her breathe .
Visitors throughout Miss Taylor 's hospitalization included her four children , Maria Burton - Carson , Liza Todd - Tivery and Christopher and Michael Wilding .
