Category 5 hurricanes include the 1935 storm striking the Florida Keys , 1969 's Camille striking Mississippi and Louisiana , 1988 's Gilbert striking from the Lesser Antilles to Mexico ,
and 1989 's Hugo striking the Lesser Antilles and South Carolina .
Other killer hurricanes struck Galveston in 1900 , the Florida Keys in 1965
( Betsy ) ,
the Dominican Republic in 1987
( Emily ) ,
Central America in 1988
( Joan ) ,
the Gulf of Mexico in 1989
( Chantal ) ,
and Mexico in 1990
( Diana ) .
Hurricanes also hit Miami in 1926 , 1947 , 1949 , 1950 and 1964
( Cleo )
;
the Florida Keys in 1960
( Donna )
and 1987
( Floyd )
;
Mississippi , Alabama and Florida in 1985
( Elena )
;
and Mexico in 1985
( Debby ) .
